baseURL = 'https://zhujianghan.github.io/zjh-blog/'
languageCode = 'zh-cn'
title = "Fourleaf Blog"
theme = 'tailwind-blog-theme'

[outputs]
home = ['HTML', 'RSS', 'Algolia']

[outputFormats.Algolia]
baseName = 'algolia'
isPlainText = true
mediaType = 'application/json'
notAlternative = true

[params.algolia]
vars = ['title', 'summary', 'date', 'publishdate', 'expirydate', 'permalink']
params = ['categories', 'tags']
appId = 'QB1NYV0GE1'
indexName = 'hugo-tailwind-blog'
searchOnlyKey = '87c867dd34150cbfbee6b6e819fb7c5c'

[params]
enableComment = true