[[main]]
name = 'Frontend'
url = 'posts/frontend'
weight = -109

[[main]]
name = 'Backend'
url = 'posts/backend'
weight = -108

[[main]]
name = 'Server'
url = 'posts/server'
weight = -107

[[main]]
name = 'Interview'
url = 'posts/interview'
weight = -106

[[main]]
name = 'Other'
url = 'posts/other'
weight = -105

[[link]]
name = 'Github'
weight = 1
url = 'https://github.com/#'