[[main]]
name = '前端'
url = 'posts/frontend'
weight = -109

[[main]]
name = '后端'
url = 'posts/backend'
weight = -108

[[main]]
name = '服务器'
url = 'posts/server'
weight = -107

[[main]]
name = '面试题'
url = 'posts/interview'
weight = -106

[[main]]
name = '其它'
url = 'posts/other'
weight = -105

[[link]]
name = 'Github'
weight = 1
url = 'https://github.com/#'